/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/*
 * Copyright 2023 Rivos, Inc
 */

#ifndef _UAPI_ASM_HWPROBE_H
#define _UAPI_ASM_HWPROBE_H

#include <linux/types.h>

/*
 * Interface for probing hardware capabilities from userspace, see
 * Documentation/arch/riscv/hwprobe.rst for more information.
 */
struct riscv_hwprobe {
	__s64 key;
	__u64 value;
};

#define RISCV_HWPROBE_KEY_MVENDORID	0
#define RISCV_HWPROBE_KEY_MARCHID	1
#define RISCV_HWPROBE_KEY_MIMPID	2
#define RISCV_HWPROBE_KEY_BASE_BEHAVIOR	3
#define		RISCV_HWPROBE_BASE_BEHAVIOR_IMA	BIT_ULL(0)
#define RISCV_HWPROBE_KEY_IMA_EXT_0	4
#define		RISCV_HWPROBE_IMA_FD		BIT_ULL(0)
#define		RISCV_HWPROBE_IMA_C		BIT_ULL(1)
#define		RISCV_HWPROBE_IMA_V		BIT_ULL(2)
#define		RISCV_HWPROBE_EXT_ZBA		BIT_ULL(3)
#define		RISCV_HWPROBE_EXT_ZBB		BIT_ULL(4)
#define		RISCV_HWPROBE_EXT_ZBS		BIT_ULL(5)
#define		RISCV_HWPROBE_EXT_ZICBOZ	BIT_ULL(6)
#define		RISCV_HWPROBE_EXT_ZBC		BIT_ULL(7)
#define		RISCV_HWPROBE_EXT_ZBKB		BIT_ULL(8)
#define		RISCV_HWPROBE_EXT_ZBKC		BIT_ULL(9)
#define		RISCV_HWPROBE_EXT_ZBKX		BIT_ULL(10)
#define		RISCV_HWPROBE_EXT_ZKND		BIT_ULL(11)
#define		RISCV_HWPROBE_EXT_ZKNE		BIT_ULL(12)
#define		RISCV_HWPROBE_EXT_ZKNH		BIT_ULL(13)
#define		RISCV_HWPROBE_EXT_ZKSED		BIT_ULL(14)
#define		RISCV_HWPROBE_EXT_ZKSH		BIT_ULL(15)
#define		RISCV_HWPROBE_EXT_ZKT		BIT_ULL(16)
#define		RISCV_HWPROBE_EXT_ZVBB		BIT_ULL(17)
#define		RISCV_HWPROBE_EXT_ZVBC		BIT_ULL(18)
#define		RISCV_HWPROBE_EXT_ZVKB		BIT_ULL(19)
#define		RISCV_HWPROBE_EXT_ZVKG		BIT_ULL(20)
#define		RISCV_HWPROBE_EXT_ZVKNED	BIT_ULL(21)
#define		RISCV_HWPROBE_EXT_ZVKNHA	BIT_ULL(22)
#define		RISCV_HWPROBE_EXT_ZVKNHB	BIT_ULL(23)
#define		RISCV_HWPROBE_EXT_ZVKSED	BIT_ULL(24)
#define		RISCV_HWPROBE_EXT_ZVKSH		BIT_ULL(25)
#define		RISCV_HWPROBE_EXT_ZVKT		BIT_ULL(26)
#define		RISCV_HWPROBE_EXT_ZFH		BIT_ULL(27)
#define		RISCV_HWPROBE_EXT_ZFHMIN	BIT_ULL(28)
#define		RISCV_HWPROBE_EXT_ZIHINTNTL	BIT_ULL(29)
#define		RISCV_HWPROBE_EXT_ZVFH		BIT_ULL(30)
#define		RISCV_HWPROBE_EXT_ZVFHMIN	BIT_ULL(31)
#define		RISCV_HWPROBE_EXT_ZFA		BIT_ULL(32)
#define		RISCV_HWPROBE_EXT_ZTSO		BIT_ULL(33)
#define		RISCV_HWPROBE_EXT_ZACAS		BIT_ULL(34)
#define		RISCV_HWPROBE_EXT_ZICOND	BIT_ULL(35)
#define		RISCV_HWPROBE_EXT_ZIHINTPAUSE	BIT_ULL(36)
#define		RISCV_HWPROBE_EXT_ZVE32X	BIT_ULL(37)
#define		RISCV_HWPROBE_EXT_ZVE32F	BIT_ULL(38)
#define		RISCV_HWPROBE_EXT_ZVE64X	BIT_ULL(39)
#define		RISCV_HWPROBE_EXT_ZVE64F	BIT_ULL(40)
#define		RISCV_HWPROBE_EXT_ZVE64D	BIT_ULL(41)
#define		RISCV_HWPROBE_EXT_ZIMOP		BIT_ULL(42)
#define		RISCV_HWPROBE_EXT_ZCA		BIT_ULL(43)
#define		RISCV_HWPROBE_EXT_ZCB		BIT_ULL(44)
#define		RISCV_HWPROBE_EXT_ZCD		BIT_ULL(45)
#define		RISCV_HWPROBE_EXT_ZCF		BIT_ULL(46)
#define		RISCV_HWPROBE_EXT_ZCMOP		BIT_ULL(47)
#define		RISCV_HWPROBE_EXT_ZAWRS		BIT_ULL(48)
#define RISCV_HWPROBE_KEY_CPUPERF_0	5
#define		RISCV_HWPROBE_MISALIGNED_UNKNOWN	(0 << 0)
#define		RISCV_HWPROBE_MISALIGNED_EMULATED	(1 << 0)
#define		RISCV_HWPROBE_MISALIGNED_SLOW		(2 << 0)
#define		RISCV_HWPROBE_MISALIGNED_FAST		(3 << 0)
#define		RISCV_HWPROBE_MISALIGNED_UNSUPPORTED	(4 << 0)
#define		RISCV_HWPROBE_MISALIGNED_MASK		(7 << 0)
#define RISCV_HWPROBE_KEY_ZICBOZ_BLOCK_SIZE	6
#define RISCV_HWPROBE_KEY_HIGHEST_VIRT_ADDRESS	7
#define RISCV_HWPROBE_KEY_TIME_CSR_FREQ	8
/* Increase RISCV_HWPROBE_MAX_KEY when adding items. */

/* Flags */
#define RISCV_HWPROBE_WHICH_CPUS	BIT(0)

#endif
