obj-$(CONFIG_RIVOS_PWC) += rivos-pwc.o \
			   rivos-pwc-dpa-perf.o \
			   rivos-pwc-common.o \
			   rivos-pwc-power.o \
			   rivos-pwc-dimm-power.o \
			   rivos-pwc-simple-power.o \
			   rivos-pwc-soc-power.o \
			   rivos-pwc-thermal.o \
			   rivos-pwc-chiplet-thermal.o \
			   rivos-pwc-dimm-thermal.o \
			   rivos-pwc-dpa-thermal.o \
			   rivos-pwc-hbm-thermal.o \
			   rivos-pwc-soc-thermal.o
